name: Build Android
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      MODE: release
      TARGET_OS: android
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019,windows-2022,macos-11,macos-12]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      timeout-minutes: 5
      with:
        ndk-version: r21e

    - name: Build
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        make -v
        make TARGET_ARCH=x64 -j4
        make TARGET_ARCH=x86 -j4
        make TARGET_ARCH=arm64 -j4
        make TARGET_ARCH=arm -j4
