name: Build MacOS
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      MODE: release
      TARGET_OS: osx
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11,macos-12]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Make (build)
      run: |
        make -v
        clang++ -v
        make TARGET_ARCH=x64 -j${{ env.JOBS }}
        make TARGET_ARCH=arm64 -j${{ env.JOBS }}

    - name: Make (dist)
      run: |
        make dist -j${{ env.JOBS }}
      
    - name: Test
      run: |
        ./dist/osx-10.15/CppCore.Test.app/Contents/MacOS/CppCore.Test

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Packages (${{ matrix.os }})
        path: |
          ./dist/osx-10.15/CppCore.Example.Server.pkg
          ./dist/osx-10.15/CppCore.Example.Client.pkg
          ./dist/osx-10.15/CppCore.Test.pkg
          ./dist/osx-10.15/CppCore.Debug.pkg
